version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "2027"
      MYSQL_DATABASE: devops_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: notevault-app
    depends_on:
      - mysql
    ports:
      - "5000:5000"

volumes:
  mysql-data: